#define		SegByte	 	_pd
#define		SegByteC	_pdc	
#define		SEG1		_pd0
#define		SEG2		_pd1
#define		SEG3		_pd2
#define		SEG4		_pd3
#define		SEG5		_pd4
#define		SEG6		_pd5
#define		SEG7		_pd6
#define		SEG8		_pd7
#define		SEG9		_pe0
#define		SEG9C		_pec0
#define		COM0		_pc0
#define		COM0C		_pcc0
#define		COM1		_pc1
#define		COM1C		_pcc1
#define		COM2		_pc6
#define		COM2C		_pcc6
#define		COM3		_pc7
#define		COM3C		_pcc7

#define		Col			0x80			
#define		_C			0x80
#define		AM			0x80
#define		PM			0x80

#define		SW_AdjPU	_pepu2
#define		SW_Adj		_pe2
#define		SW_AdjC		_pec2
#define		SW_EnterPU	_pepu3
#define		SW_Enter	_pe3
#define		SW_EnterC	_pec3

#define		SPK		   	_pc5
#define		SPKC		_pcc5