#define	IR_Pin			_pc3		//PC.3
#define	IR_PinC			_pcc3		//PCC.3
#define	IR_PinPU		_pcpu3		//PCC.3

#define LCM_RS			_ph0		//PE.0
#define LCM_RW			_ph1		//PE.1
#define	LCM_EN			_ph2		//PE.2
#define LCM_RSC			_phc0		//PEC.0
#define LCM_RWC			_phc1		//PEC.1
#define LCM_ENC			_phc2		//PEC.2
#define LCM_DataPort	_pg
#define LCM_DataPortC	_pgc


#define LEDPort			_pd
#define LEDPortC		_pdc
#define pLED0			_pd0
#define pLED1			_pd1
#define pLED2			_pd2
#define pLED3			_pd3

#define CID				0xFF00
#define LED0			0xBA45
#define LED1			0xBB44
#define LED2			0xF807
#define LED3			0xE916

#define LED0_			0xB946
#define LED1_			0xBF40
#define LED2_			0xEA15
#define LED3_			0xE619
