#define LCM_EN			_ph2	//PE.0
#define LCM_ENC			_phc2	//PEC.0
#define LCM_RW			_ph1	//PE.1
#define LCM_RWC			_phc1	//PEC.1
#define LCM_RS			_ph0	//PE.2
#define LCM_RSC			_phc0	//PEC.2
#define LCM_DataPort	_pg
#define LCM_DataPortC	_pgc

#define SW_Great		_pe5	
#define SW_Less			_pe6	
#define SW_Enter		_pe7	
#define SW_GreatC		_pec5	
#define SW_LessC		_pec6	
#define SW_EnterC		_pec7	
#define SW_GreatPU		_pepu5	
#define SW_LessPU		_pepu6	
#define SW_EnterPU		_pepu7	
