#define LCM_EN			_ph2	
#define LCM_ENC			_phc2
#define LCM_RW			_ph1
#define LCM_RWC			_phc1	
#define LCM_RS			_ph0
#define LCM_RSC			_phc0
#define LCM_DataPort	_pg
#define LCM_DataPortC	_pgc

#define SW_Period		_pe6	
#define SW_PeriodC		_pec6	
#define SW_PeriodPU		_pepu6	
#define SW_TON			_pe7	
#define SW_TONC			_pec7	
#define SW_TONPU		_pepu7	

//#define	PC4				_pc4	//PC.4
//#define	PCC4			_pcc4	//PCC.4
//#define	PA0				_pa0	//PA.0
//#define	PAC0			_pac0	//PAC.0


