#define LCM_EN			_ph2	//PE.0
#define LCM_ENC			_phc2	//PEC.0
#define LCM_RW			_ph1	//PE.1
#define LCM_RWC			_phc1	//PEC.1
#define LCM_RS			_ph0	//PE.2
#define LCM_RSC			_phc0	//PEC.2
#define LCM_DataPort	_pg
#define LCM_DataPortC	_pgc

#define SW_Faster		_pe5	
#define SW_Slower		_pe6	
#define SW_Hit			_pe7	
#define SW_FasterC		_pe5	
#define SW_SlowerC		_pe6	
#define SW_HitC			_pe7	
#define SW_FasterPU		_pepu5	
#define SW_SlowerPU		_pepu6	
#define SW_HitPU		_pepu7	

